# Generated by Django 4.0.6 on 2022-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlinks',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='cho biết đang ở trang nào'),
        ),
        migrations.AlterField(
            model_name='navlinks',
            name='link',
            field=models.CharField(max_length=100, verbose_name='link của menu'),
        ),
        migrations.AlterField(
            model_name='navlinks',
            name='text',
            field=models.CharField(max_length=50, verbose_name='text hiện ra trên menu'),
        ),
    ]
