# Generated by Django 4.0.6 on 2022-07-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_navlink_delete_navlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text hiện ra trên menu')),
            ],
        ),
    ]
