# Generated by Django 4.0.6 on 2022-07-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_testitem_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlink',
            name='postition',
            field=models.IntegerField(blank=True, default=0, verbose_name='thứ tự menu'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='link',
            field=models.CharField(max_length=100, verbose_name='link của menu item'),
        ),
    ]
