# Generated by Django 4.0.6 on 2022-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Mail công ty'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='facebook',
            field=models.URLField(blank=True, max_length=128, verbose_name='Link facebook'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='linkedin',
            field=models.URLField(blank=True, max_length=128, verbose_name='Link linkedin'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Điện thoại'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='twitter',
            field=models.URLField(blank=True, max_length=128, verbose_name='Link twitter'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tên công ty'),
        ),
    ]
