# Generated by Django 4.0.6 on 2022-07-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_companyinfo_address_companyinfo_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Họ tên')),
                ('title', models.CharField(max_length=50, verbose_name='Chức vụ')),
                ('description', models.TextField(verbose_name='Thông tin')),
                ('image', models.CharField(blank=True, max_length=128, verbose_name='Hình')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên dự án')),
                ('sumary', models.CharField(blank=True, max_length=200, verbose_name='Tóm tắt')),
                ('image', models.CharField(blank=True, max_length=128, verbose_name='Hình')),
            ],
        ),
        migrations.AddField(
            model_name='testitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='hình'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên công ty'),
        ),
    ]
