# Generated by Django 4.0.6 on 2022-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_boardmember_project_testitem_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=30)),
                ('email', models.EmailField(help_text='Your email', max_length=254)),
                ('message', models.TextField(help_text='Write here your message!', max_length=2000)),
            ],
        ),
    ]
